### PR TITLE
Add TransferHooks, Budget fix and upgrade to Polkadot v0.9.36

### PR DESCRIPTION
**Pull request by HashWarlock**
### TransferHooks implementation
For implementations downstream of the RMRK pallet there needs to be an ability to add custom logic in the case that there are multiple pallets using the RMRK NFT pallet, but want to keep the business logic mutually exclusive. This implementation allows for a trait called `TransferHooks` to be implemented with 2 functions `pre_check` and `post_transfer` that default to `true` when not implemented.

### Budget trait fix
There are 2 problems with the current Budget trait:

NFTs are currently allowed to mint and send NFTs to a parent NFT that can meet up to the threshold of NestingBudget::get() + 1. This allows for NFTs queries like lookup_root_owner to return errors like TooManyRecursions. Having this error is okay, but the NFTs should be prevented from being minted to or sent to a parent NFT if the Budget threshold is met.

Currently the code will do a calculation on functions like burn_nft and this will perform an arithmetic subtraction at the end of the function, but this should be added as a field in the Value type & implement a function from Budget to get the budget that has been consumed and budget that is left.

### Update pallet index macro for pallet functions
This is a small change introduced in `polkadot-v0.9.36` to add the pallet index

## Targets
- [x] Upgrade to `polkadot-v0.9.36`
- [x] implement `TransferHooks` trait with `pre_check` and `post_transfer` functions
- [x] Update integration tests
- [x] Fix minting/sending NFTs that exceed the threshold of `NestingBudget::get()` value.
- [x] Add fields names `budget_consumed` and budget_left` to track & through errors is an overflow is detected.
- [x] Add functions in `Budget` trait to get the 2 new fields.
- [x] Fix benchmarking errors from Traits being renamed.
- [x] Add pallet index for pallet functions.

### CODE REVIEW

**Review by ilionic — APPROVED** [review]
LGTM
merged current main to `polkadot-v0.9.29`.
Let's merge this one so other benchmarking PRs could be updated as well.
Thank you!

**Comment by HashWarlock** [comment]
> LGTM merged current main to `polkadot-v0.9.29`. Let's merge this one so other benchmarking PRs could be updated as well. Thank you!

I need to fix an odd build error. I didn't see this building and running locally. I'll have update asap.

**Comment by ilionic** [comment]
@HashWarlock do you think we can merge this one? So we can update other benchmarking PRs with API changes

**Comment by HashWarlock** [comment]
> @HashWarlock do you think we can merge this one? So we can update other benchmarking PRs with API changes

Good to merge now. Then we can update the rest

**Pull request merged**
