### PR TITLE
Upgrade to polkadot-v0.9.26

### PR DESCRIPTION
**Pull request by HashWarlock**
Upgrade to `polkadot-v0.9.26`

### CODE REVIEW

**Review by h4x3rotab — APPROVED** [review]
LGTM

**Comment by h4x3rotab** [comment]
I suggest to maintain a branch for each Polkadot release in the repo

**Comment by HashWarlock** [comment]
> I suggest to maintain a branch for each Polkadot release in the repo

Created branch for [polkadot-v0.9.24](https://github.com/rmrk-team/rmrk-substrate/tree/polkadot-v0.9.24)

**Review by ilionic — APPROVED** [review]
Good to merge

**Review by rdovgan — APPROVED** [review]

**Pull request merged**
