### PR TITLE
Add pallet_utility

### PR DESCRIPTION
**Pull request by zabuxx**
Add support for pallet_utility to enable batches.

### CODE REVIEW

**Comment by KaiserKarel** [comment]
Is there a particular reason why you would like to have `pallet_utility` added? The RMRK pallets are intended to be used as library components. The included runtime here will eventually be discarded.

**Comment by h4x3rotab** [comment]
Sounds ok for testing and especially regression test with polkadot.js. More context is welcome

**Comment by zabuxx** [comment]
It enables creating batch transactions, allowing for example creation of multiple NFTs at once. This functionality is exposed via  polkadot api.tx.utility.batch()

It is also needed for  [rmrk-team / rmrk1-seeder-scripts](https://github.com/rmrk-team/rmrk1-seeder-scripts)

**Comment by ilionic** [comment]
thanks @zabuxx, merging.

**Pull request merged**
