### PR TITLE
Disable pallet uniques calls

### LINKED ISSUE #150: Minting in Uniques Pallet Corrupts RMRK Minting
Found a bug in the following scenario:
1. Alice creates collection 0
2. Alice calls mint_nft in RMRK core pallet
3. Alice calls mint in Uniques pallet
4. Alice calls mint_nft in RMRK core pallet

Step 4 throws an error from Uniques pallet with `AlreadyExists` bc the NFT ID incremented from the Uniques pallet, but the RMRK NFT ID did not causing them to be out of sync & RMRK tries to mint an NFT ID that already exists in Uniques.

### LINKED ISSUE #151: Restrict direct pallet_uniques calls
Using `BaseCallFilter` disable direct calls to `pallet_uniques` since it could lead to unexpected bugs in rmrk pallets if calling uniques extrinsics  directly. 

[Example](https://github.com/paritytech/cumulus/blob/2fe7a2edba05155c6a5f0f3527e1001aad7aee2e/polkadot-parachains/statemint/src/lib.rs#L126)

### PR DESCRIPTION
**Pull request by ilionic**
Fixes #151
Fixes #150

### CODE REVIEW

**Review by HashWarlock — APPROVED** [review]
Looks good.

**Comment by bmacer** [comment]
Looks good.  I tried to implement a test of this on rmrk-core but failed.  Not sure how I did it wrong.

I added this to the [mock.rs](https://github.com/rmrk-team/rmrk-substrate/blob/036cc638fadd55df2081503e2bbd0ff69f1bca05/pallets/rmrk-core/src/mock.rs)
https://github.com/rmrk-team/rmrk-substrate/blob/036cc638fadd55df2081503e2bbd0ff69f1bca05/runtime/src/lib.rs#L169-L193

Changed `BaseCallFilter` to equal `BaseFilter`
https://github.com/rmrk-team/rmrk-substrate/blob/036cc638fadd55df2081503e2bbd0ff69f1bca05/runtime/src/lib.rs#L199

And wrote this test (not really a test yet just a println, but the result is unexpected/unwanted "Ok(())"
```
/// Uniques: Unable to call directly
#[test]
fn calling_uniques_directly_fails() {
	ExtBuilder::default().build().execute_with(|| {
		println!("{:?}", Uniques::create(Origin::signed(ALICE),1, ALICE));
	});
}
```

If a test for this doesn't matter that much, go ahead and merge.  Otherwise, any ideas?

**Review by bmacer — APPROVED** [review]
Looks good unless you want to pursue testing this behavior

**Comment by HashWarlock** [comment]
> Looks good. I tried to implement a test of this on rmrk-core but failed. Not sure how I did it wrong.
> 
> I added this to the [mock.rs](https://github.com/rmrk-team/rmrk-substrate/blob/036cc638fadd55df2081503e2bbd0ff69f1bca05/pallets/rmrk-core/src/mock.rs)
> 
> https://github.com/rmrk-team/rmrk-substrate/blob/036cc638fadd55df2081503e2bbd0ff69f1bca05/runtime/src/lib.rs#L169-L193
> 
> Changed `BaseCallFilter` to equal `BaseFilter`
> 
> https://github.com/rmrk-team/rmrk-substrate/blob/036cc638fadd55df2081503e2bbd0ff69f1bca05/runtime/src/lib.rs#L199
> 
> And wrote this test (not really a test yet just a println, but the result is unexpected/unwanted "Ok(())"
> 
> ```
> /// Uniques: Unable to call directly
> #[test]
> fn calling_uniques_directly_fails() {
> 	ExtBuilder::default().build().execute_with(|| {
> 		println!("{:?}", Uniques::create(Origin::signed(ALICE),1, ALICE));
> 	});
> }
> ```
> 
> If a test for this doesn't matter that much, go ahead and merge. Otherwise, any ideas?

Check out the test file in substrate and this example https://github.com/paritytech/substrate/blob/master/frame/utility/src/tests.rs#L277-L292

We should get an `frame_system::Error::<Test>::CallFiltered`.

**Comment by ilionic** [comment]
Will merge for now as filtered Calls not part of rmrk pallets technically. But I guess good to add a test anyway

**Pull request merged**
