### PR TITLE
fix issue 208 allow minting after burn

### PR DESCRIPTION
**Pull request by bmacer**
addresses #208

### CODE REVIEW

**Review by ilionic — CHANGES_REQUESTED** [review]
Please run and fix integration test:
```
  1) integration test: lock collection
       lock collection with minting:

      AssertionError: expected +0 to equal 5
      + expected - actual

      -0
      +5

```

**Comment by ilionic** [comment]
@bmacer yes integration tests pass now, but unit test fails:
```
failures:

---- tests::lock_collection_works stdout ----
thread 'tests::lock_collection_works' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(Module(ModuleError { index: 2, error: [14, 0, 0, 0], message: Some("CollectionFullOrLocked") }))`', pallets/rmrk-core/src/tests.rs:149:9
 ````

**Review by ilionic — CHANGES_REQUESTED** [review]
Please adjust unit test

**Comment by bmacer** [comment]
@ilionic 
Turns out when I merged main, I undid my changes, so we returned to the original state.  I fixed this.
The integration test was failing because it was checking that `max` for the collection == collection size, which is the logic we changed.  Now in all cases, `max` is set to 0 on locking.  I changed the integration test to reflect this, and the test `testLockCollection` is now passing.  Also, unit tests are passing.  Should be good now.

**Review by ilionic — APPROVED** [review]
Thanks @bmacer, LGTM
@HashWarlock please take a look and feel free to merge if all good.

**Pull request merged**
